[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "codegen"
version = "0.1.0"
description = "CodeGen tool"
authors = [{ name="Your Name", email="you@example.com" }]
dependencies = []
